name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: checkout dependent peak repo
      uses: actions/checkout@v2
      with:
            repository: cdonovick/peak
            path: ./peak
    - name: Install dependencies
      run: |
        #conda env update --file environment.yml --name base
        pip install -e .
        cd peak; pip install -e .; cd ..;
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests/.
